// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesApp.Infrastructure.Data;

#nullable disable

namespace MoviesApp.Infrastructure.Migrations
{
    [DbContext(typeof(MoviesDbContext))]
    [Migration("20250506013705_Initial-Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoviesApp.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = 12,
                            Name = "Inception",
                            Rating = 9,
                            Year = 2010
                        },
                        new
                        {
                            Id = 2,
                            Genre = 0,
                            Name = "The Dark Knight",
                            Rating = 10,
                            Year = 2008
                        },
                        new
                        {
                            Id = 3,
                            Genre = 12,
                            Name = "Interstellar",
                            Rating = 9,
                            Year = 2014
                        },
                        new
                        {
                            Id = 4,
                            Genre = 11,
                            Name = "Titanic",
                            Rating = 8,
                            Year = 1997
                        },
                        new
                        {
                            Id = 5,
                            Genre = 12,
                            Name = "The Matrix",
                            Rating = 9,
                            Year = 1999
                        },
                        new
                        {
                            Id = 6,
                            Genre = 2,
                            Name = "Avatar",
                            Rating = 8,
                            Year = 2009
                        },
                        new
                        {
                            Id = 7,
                            Genre = 0,
                            Name = "Gladiator",
                            Rating = 9,
                            Year = 2000
                        },
                        new
                        {
                            Id = 8,
                            Genre = 4,
                            Name = "The Godfather",
                            Rating = 10,
                            Year = 1972
                        },
                        new
                        {
                            Id = 9,
                            Genre = 4,
                            Name = "Shawshank Redemption",
                            Rating = 10,
                            Year = 1994
                        },
                        new
                        {
                            Id = 10,
                            Genre = 6,
                            Name = "Forrest Gump",
                            Rating = 9,
                            Year = 1994
                        },
                        new
                        {
                            Id = 11,
                            Genre = 1,
                            Name = "The Lion King",
                            Rating = 8,
                            Year = 1994
                        },
                        new
                        {
                            Id = 12,
                            Genre = 0,
                            Name = "Avengers: Endgame",
                            Rating = 9,
                            Year = 2019
                        },
                        new
                        {
                            Id = 13,
                            Genre = 13,
                            Name = "Parasite",
                            Rating = 9,
                            Year = 2019
                        },
                        new
                        {
                            Id = 14,
                            Genre = 4,
                            Name = "Joker",
                            Rating = 8,
                            Year = 2019
                        },
                        new
                        {
                            Id = 15,
                            Genre = 9,
                            Name = "Frozen",
                            Rating = 7,
                            Year = 2013
                        },
                        new
                        {
                            Id = 16,
                            Genre = 8,
                            Name = "The Silence of the Lambs",
                            Rating = 9,
                            Year = 1991
                        },
                        new
                        {
                            Id = 17,
                            Genre = 3,
                            Name = "The Grand Budapest Hotel",
                            Rating = 8,
                            Year = 2014
                        },
                        new
                        {
                            Id = 18,
                            Genre = 0,
                            Name = "Spider-Man: No Way Home",
                            Rating = 9,
                            Year = 2021
                        },
                        new
                        {
                            Id = 19,
                            Genre = 9,
                            Name = "Whiplash",
                            Rating = 9,
                            Year = 2014
                        },
                        new
                        {
                            Id = 20,
                            Genre = 0,
                            Name = "Mad Max: Fury Road",
                            Rating = 9,
                            Year = 2015
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
