// <auto-generated />
using System;
using BPTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BPTracker.Migrations
{
    [DbContext(typeof(BPTrackerDbContext))]
    [Migration("20241008223516_Add-Position-Table")]
    partial class AddPositionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BPTracker.Models.BloodPressure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Diastolic")
                        .HasColumnType("int");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Systolic")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Readings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2021, 10, 1),
                            Diastolic = 80,
                            PositionId = "1",
                            Systolic = 120
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2021, 10, 2),
                            Diastolic = 90,
                            PositionId = "3",
                            Systolic = 130
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2021, 10, 3),
                            Diastolic = 100,
                            PositionId = "1",
                            Systolic = 140
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2021, 10, 4),
                            Diastolic = 110,
                            PositionId = "2",
                            Systolic = 150
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2021, 10, 5),
                            Diastolic = 120,
                            PositionId = "2",
                            Systolic = 160
                        });
                });

            modelBuilder.Entity("BPTracker.Models.Position", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Standing"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Sitting"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Lying down"
                        });
                });

            modelBuilder.Entity("BPTracker.Models.BloodPressure", b =>
                {
                    b.HasOne("BPTracker.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
