// <auto-generated />
using System;
using BPTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BPTracker.Migrations
{
    [DbContext(typeof(BPTrackerDbContext))]
    [Migration("20241008223219_Initial-Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BPTracker.Models.BloodPressure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Diastolic")
                        .HasColumnType("int");

                    b.Property<int>("Systolic")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Readings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2021, 10, 1),
                            Diastolic = 80,
                            Systolic = 120
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2021, 10, 2),
                            Diastolic = 90,
                            Systolic = 130
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2021, 10, 3),
                            Diastolic = 100,
                            Systolic = 140
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2021, 10, 4),
                            Diastolic = 110,
                            Systolic = 150
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2021, 10, 5),
                            Diastolic = 120,
                            Systolic = 160
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
